from transformer import contact_to_icloud_contact, icloud_contact_to_contact

contact_to_icloud_contact = contact_to_icloud_contact.contact_to_icloud_contact
icloud_contact_to_contact = icloud_contact_to_contact.icloud_contact_to_contact
